spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=CTT
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: 172.30.8.74:8848
        cluster-name: BJ
    sentinel:
      transport:
        #指定sentinel 控制台的地址
        dashboard: 172.30.8.74:8080 #127.0.0.1:8080
      web-context-unify: false
      #打开/关闭掉对Spring MVC端点的保护
      filter:
        enabled: true
    stream:
      rocketmq:
        binder:
          name-server: 172.30.8.74:9876
        bindings:
          output:
            producer:
              # 实现事务
              transactional: true
              group: tx-sync-user-group
      bindings:
        output:
          # 用来指定topic
          destination: stream-test-topic
        my-output:
          destination: stream-my-topic
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090


#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 想要调用的微服务的名称 user-center, default:全局
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求;而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  #okhttp:
    #enabled: true
  # 为feign整合sentinel
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate注解
    enabled: false

rocketmq:
  name-server: 172.30.8.74:9876
  producer:
    # 小坑：必须指定group
    group: test-group

jwt:
  secret: 374052753
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600