spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=CTT
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: 172.30.8.74:8848
        cluster-name: BJ
    sentinel:
      transport:
        #指定sentinel 控制台的地址
        dashboard: 172.30.8.74:8080 #127.0.0.1:8080
      web-context-unify: false
      #关闭掉对Spring MVC端点的保护
      filter:
        enabled: false
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090


#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 想要调用的微服务的名称 user-center, default:全局
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求;而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true
  # 为feign整合sentinel
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate注解
    enabled: false
