spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=CTT
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: 172.30.8.74:8848
        cluster-name: BJ
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
server:
  port: 8090


#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
